// Original ambient score: D minor / suspended chords, 84 BPM.
// All instruments, percussion and effects are synthesized locally.
export class AudioEngine {
  constructor(){this.ctx=null;this.master=null;this.musicGain=null;this.sfxGain=null;this.enabled=false;this.musicVolume=0.38;this.sfxVolume=0.55;this.step=0;this.nextBeat=0;this.scheduler=null;this.voices=0;this.lastEffect=0;this.active=true;}
  async unlock(){try{if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.musicGain=this.ctx.createGain();this.sfxGain=this.ctx.createGain();this.master.gain.value=0.7;this.musicGain.connect(this.master);this.sfxGain.connect(this.master);const compressor=this.ctx.createDynamicsCompressor();compressor.threshold.value=-16;compressor.ratio.value=5;this.master.connect(compressor);compressor.connect(this.ctx.destination);this.nextBeat=this.ctx.currentTime;this.scheduler=setInterval(()=>this.schedule(),100);}if(this.ctx.state==='suspended')await this.ctx.resume();this.applyVolumes();}catch{this.enabled=false;}}
  applyVolumes(){if(!this.ctx)return;const t=this.ctx.currentTime;this.musicGain.gain.setTargetAtTime(this.enabled&&this.active?this.musicVolume:0,t,0.12);this.sfxGain.gain.setTargetAtTime(this.enabled&&this.active?this.sfxVolume:0,t,0.03);}
  setEnabled(v){this.enabled=v;if(v)this.unlock();this.applyVolumes();}
  setActive(v){this.active=v;this.applyVolumes();if(v&&this.ctx)this.nextBeat=this.ctx.currentTime;}
  note(freq,time,duration=0.5,type='sine',gain=0.12,dest=this.musicGain){if(!this.ctx||this.voices>28)return;const osc=this.ctx.createOscillator(),env=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,time);env.gain.setValueAtTime(0,time);env.gain.linearRampToValueAtTime(gain,time+0.015);env.gain.exponentialRampToValueAtTime(0.001,time+duration);osc.connect(env);env.connect(dest);this.voices++;osc.onended=()=>{this.voices--;osc.disconnect();env.disconnect();};osc.start(time);osc.stop(time+duration+0.03);}
  schedule(){if(!this.ctx)return;const now=this.ctx.currentTime;if(!this.enabled||!this.active){this.nextBeat=now;return;}if(this.nextBeat<now-0.3)this.nextBeat=now;while(this.nextBeat<now+0.2){const bar=Math.floor(this.step/16)%4,beat=this.step%16,roots=[146.832,130.813,116.541,130.813],root=roots[bar],melody=[0,7,12,10,7,3,5,7,0,7,15,12,10,7,5,3];if(beat%4===0){this.note(root/2,this.nextBeat,1.7,'sine',0.22);this.note(root,this.nextBeat,2.5,'triangle',0.038);this.note(root*1.4983,this.nextBeat,2.5,'sine',0.05);}if(beat%2===0)this.note(root*2**(melody[beat]/12)*2,this.nextBeat,0.7,'sine',0.038);if(beat%4===0)this.kick(this.nextBeat);if(beat%4===2)this.note(1800,this.nextBeat,0.055,'triangle',0.008);this.nextBeat+=60/84/4;this.step++;}}
  kick(time){const o=this.ctx.createOscillator(),e=this.ctx.createGain();o.frequency.setValueAtTime(90,time);o.frequency.exponentialRampToValueAtTime(30,time+0.17);e.gain.setValueAtTime(0.11,time);e.gain.exponentialRampToValueAtTime(0.001,time+0.17);o.connect(e);e.connect(this.musicGain);o.onended=()=>{o.disconnect();e.disconnect();};o.start(time);o.stop(time+0.2);}
  effect(type){if(!this.ctx||!this.enabled||!this.active)return;const t=this.ctx.currentTime;if(['shot','kill','xp'].includes(type)&&t-this.lastEffect<0.09)return;this.lastEffect=t;
    const tones={shot:[640,.065,'triangle',.026],kill:[180,.07,'triangle',.025],xp:[1020,.085,'sine',.035],hurt:[95,.2,'sawtooth',.07],dash:[320,.17,'sine',.06],pulse:[80,.55,'triangle',.12],arc:[1450,.09,'triangle',.04],nova:[110,.25,'triangle',.07],heal:[880,.25,'sine',.065],boss:[65,.8,'sawtooth',.06]};
    if(tones[type]){const [f,d,w,v]=tones[type];this.note(f,t,d,w,v,this.sfxGain);}else if(['level','choose','evolve','won','start'].includes(type)){const notes=type==='won'?[293.665,369.994,440,587.33]:type==='evolve'?[293.665,440,587.33,880]:[440,554.365,659.255];notes.forEach((f,i)=>this.note(f,t+i*.1,.45,'sine',.065,this.sfxGain));}else if(type==='dead'){[220,174.614,146.832].forEach((f,i)=>this.note(f,t+i*.18,.6,'triangle',.05,this.sfxGain));}}
}
