import { Game, MODES, UPGRADES, formatTime } from './core.js';
import { Renderer } from './render.js';
import { AudioEngine } from './audio.js';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const icon=(name,cls='')=>`<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const DEFAULT_SETTINGS={sound:false,music:0.38,sfx:0.55,quality:'auto',vibration:true};
const EMPTY_RECORDS={runs:0,wins:0,totalKills:0,bestKills:0,bestTime:0,modes:{}};
function read(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch{return fallback;}}
function save(key,v){try{localStorage.setItem(key,JSON.stringify(v));return true;}catch{return false;}}
function number(v,fallback,min,max){return typeof v==='number'&&Number.isFinite(v)?Math.min(max,Math.max(min,v)):fallback;}
const rawSettings=read('lastlight-settings-v1',{});
const settings={...DEFAULT_SETTINGS};if(rawSettings&&typeof rawSettings==='object'){settings.sound=rawSettings.sound===true;settings.music=number(rawSettings.music,.38,0,1);settings.sfx=number(rawSettings.sfx,.55,0,1);settings.quality=['auto','low','high'].includes(rawSettings.quality)?rawSettings.quality:'auto';settings.vibration=rawSettings.vibration!==false;}
const rawRecords=read('lastlight-records-v1',{}),records={...EMPTY_RECORDS,modes:{}};if(rawRecords&&typeof rawRecords==='object'){for(const k of ['runs','wins','totalKills','bestKills','bestTime'])records[k]=Math.floor(number(rawRecords[k],0,0,1e9));for(const id of Object.keys(MODES)){const r=rawRecords.modes?.[id];if(r&&typeof r==='object')records.modes[id]={time:number(r.time,0,0,1e6),kills:Math.floor(number(r.kills,0,0,1e9)),won:r.won===true};}}
const renderer=new Renderer($('#game-canvas')),audio=new AudioEngine();renderer.setQuality(settings.quality);audio.musicVolume=settings.music;audio.sfxVolume=settings.sfx;audio.enabled=settings.sound;
let mode='guard',game=null,demo=makeDemo(),prevState='home',previous=performance.now(),accumulator=0,hudTimer=0,frameTime=0,elapsedTime=0,frameCount=0,fps=60,resultSaved=false,toastTimer=0,announceTimer=0,dialogReturn=null,installPrompt=null,waitingSW=null,pendingReload=false;const STEP=1/60;
const keys=new Set(),movement={x:0,y:0},stick={id:null,x:0,y:0};let lastArsenal='';
function makeDemo(){const g=new Game('guard',32489);g.start();g.levels.orbit=2;g.levels.frost=1;g.levels.drone=1;g.player.invincible=9999;g.viewRadius=400;g.time=12;for(let i=0;i<32;i++){const e=g.spawnEnemy(i%7===0?2:i%3===0?1:0);const a=g.rng()*Math.PI*2,r=150+g.rng()*370;e.x=Math.cos(a)*r;e.y=Math.sin(a)*r;}return g;}
function clearInput(){keys.clear();movement.x=movement.y=0;stick.id=null;$('#joystick').hidden=true;}
function syncSound(){for(const b of $$('.sound-toggle')){b.classList.toggle('muted',!settings.sound);b.setAttribute('aria-pressed',String(settings.sound));}for(const s of $$('.sound-label'))s.textContent=settings.sound?'SOUND ON':'SOUND OFF';}
function setSound(v){settings.sound=v;audio.setEnabled(v);save('lastlight-settings-v1',settings);syncSound();}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500);}
function announce(message){$('#announcement').textContent=message;$('#announcement').hidden=false;clearTimeout(announceTimer);announceTimer=setTimeout(()=>$('#announcement').hidden=true,2600);}
function hideScreens(){$$('#home-screen,#hud,#upgrade-screen,#pause-screen,#result-screen').forEach(x=>x.hidden=true);}
function start(){clearInput();game=new Game(mode);game.start();resultSaved=false;lastArsenal='';prevState='';accumulator=0;document.body.classList.add('playing');renderer.camera.x=game.player.x;renderer.camera.y=game.player.y;renderer.resize();audio.unlock();audio.setActive(true);$('#mission-label').textContent=MODES[mode].name;$('#time-target').textContent='/ '+formatTime(game.duration);$('#movement-hint').hidden=false;$('#announcement').hidden=true;transition();updateHUD();$('#stage').focus({preventScroll:true});}
function home(){if(game&&['running','paused','upgrade'].includes(game.state))storeResult(false);game=null;clearInput();prevState='home';hideScreens();$('#home-screen').hidden=false;document.body.classList.remove('playing');$('#announcement').hidden=true;$('#boss-panel').hidden=true;renderer.resize();demo=makeDemo();updateBest();$('#start-button').focus({preventScroll:true});}
function transition(){if(!game||game.state===prevState)return;prevState=game.state;clearInput();hideScreens();$('#hud').hidden=false;
  if(game.state==='upgrade'){renderUpgrades();$('#upgrade-screen').hidden=false;$('#upgrade-cards button')?.focus({preventScroll:true});}
  else if(game.state==='paused'){$('#pause-screen').hidden=false;$('#resume-button').focus({preventScroll:true});}
  else if(game.state==='dead'||game.state==='won'){renderResult();$('#result-screen').hidden=false;$('#hud').hidden=true;$('#retry-button').focus({preventScroll:true});}
}
function renderUpgrades(){const chosen=game.choices;$('#upgrade-cards').innerHTML=chosen.map((u,i)=>{const lv=game.levels[u.id],evolved=lv===4&&u.tag==='WEAPON';const desc=lv>0&&u.effect?u.effect[lv-1]:u.description;return `<button class="upgrade-card ${evolved?'evolve':''}" data-upgrade="${u.id}" aria-label="${u.name}を選択"><div class="upgrade-top"><span>${evolved?'EVOLUTION':lv===0?'NEW '+u.tag:u.tag}</span><span>0${i+1}</span></div><div class="upgrade-icon" style="color:${u.color}">${icon(u.icon)}</div><h3>${u.name}${evolved?'・極':''}</h3><p>${desc}</p><span class="upgrade-level">${lv===0?'ACQUIRE':`LV. ${lv} → ${lv+1}`} <span>${'▰'.repeat(lv+1)}${'▱'.repeat(u.max-lv-1)}</span></span></button>`;}).join('');}
function choose(id){if(game?.chooseUpgrade(id)){accumulator=0;prevState='';transition();updateHUD();}}
function storeResult(won){if(!game||resultSaved)return false;resultSaved=true;const best=game.time>records.bestTime||game.kills>records.bestKills;records.runs++;if(won)records.wins++;records.totalKills+=game.kills;records.bestTime=Math.max(records.bestTime,game.time);records.bestKills=Math.max(records.bestKills,game.kills);const old=records.modes[game.mode]||{time:0,kills:0,won:false};records.modes[game.mode]={time:Math.max(old.time,game.time),kills:Math.max(old.kills,game.kills),won:old.won||won};if(!save('lastlight-records-v1',records))toast('この環境では記録を保存できません。プレイは続けられます。');return best;}
function renderResult(){const won=game.state==='won',best=storeResult(won);$('#result-eyebrow').textContent=won?'YOU KEPT THE LIGHT':'THE LIGHT WILL RETURN';$('#result-title').textContent=won?'夜明けが、来た。':'次の夜へ。';$('#result-copy').textContent=won?'あなたの灯火が、荒野に朝を連れてきた。':'その灯火は、まだあなたの中に。';$('#result-time').textContent=formatTime(game.time);$('#result-kills').textContent=game.kills.toLocaleString();$('#result-level').textContent=game.level;$('#new-record').hidden=!best;$('#result-build').innerHTML=UPGRADES.filter(u=>u.tag==='WEAPON'&&game.levels[u.id]>0).map(u=>`<span title="${u.name}">${icon(u.icon)} ${game.levels[u.id]===5?'✦':game.levels[u.id]}</span>`).join('');}
function updateBest(){$('#home-best').textContent=records.bestTime?formatTime(records.bestTime):'— — : — —';}
function updateHUD(){if(!game)return;const p=game.player;$('#hp-text').textContent=`${Math.ceil(p.hp)} / ${p.maxHP}`;$('#hp-bar').style.width=`${p.hp/p.maxHP*100}%`;$('.health-track').classList.toggle('danger',p.hp<p.maxHP*.3);$('#level-text').textContent=`LV. ${String(game.level).padStart(2,'0')}`;$('#xp-bar').style.width=`${Math.min(100,game.xp/game.xpNext*100)}%`;$('#time-text').textContent=formatTime(game.time);$('#time-target').textContent=game.time>=game.duration&&!game.finalKilled?'夜の主を撃破せよ':'/ '+formatTime(game.duration);$('#kills-text').textContent=game.kills.toLocaleString();$('#movement-hint').hidden=game.time>7;
  $('#dash-cooldown').textContent=p.dashCD>0?Math.ceil(p.dashCD):'';$('#pulse-cooldown').textContent=p.pulseCD>0?Math.ceil(p.pulseCD):'';$('#dash-button').disabled=p.dashCD>0||game.state!=='running';$('#pulse-button').disabled=p.pulseCD>0||game.state!=='running';
  const signature=UPGRADES.filter(u=>u.tag==='WEAPON').map(u=>game.levels[u.id]).join(',');if(signature!==lastArsenal){lastArsenal=signature;const equipped=UPGRADES.filter(u=>u.tag==='WEAPON'&&game.levels[u.id]>0);$('#arsenal-slots').innerHTML=equipped.map(u=>`<div class="weapon-slot ${game.levels[u.id]===5?'evolved':''}" title="${u.name} Lv.${game.levels[u.id]}">${icon(u.icon)}<small>${game.levels[u.id]===5?'EVOLVE':'LV.'+game.levels[u.id]}</small></div>`).join('')+'<div class="weapon-slot empty"></div>'.repeat(6-equipped.length);}
  const boss=game.boss;$('#boss-panel').hidden=!boss?.alive;if(boss?.alive){$('#boss-name').textContent=boss.final?'夜の主 — 終夜':'夜の主 — 先触れ';$('#boss-hp').textContent=`${Math.ceil(boss.hp)} / ${Math.ceil(boss.maxHP)}`;$('#boss-bar').style.width=`${boss.hp/boss.maxHP*100}%`;}}
function processEvents(g,muted=false){for(const e of g.events){if(muted)continue;audio.effect(e.type);if(e.type==='boss')announce(e.final?'夜の主が現れた — 最後の灯火を守れ':'影が、濃くなる。夜の主が接近。');if(e.type==='bossDown')announce('夜の主を撃破');if(e.type==='evolve')announce('武器が進化した');if(e.type==='hurt'&&settings.vibration&&navigator.vibrate)navigator.vibrate(22);}g.events.length=0;}
function input(){let x=movement.x,y=movement.y;if(keys.has('KeyA')||keys.has('ArrowLeft'))x--;if(keys.has('KeyD')||keys.has('ArrowRight'))x++;if(keys.has('KeyW')||keys.has('ArrowUp'))y--;if(keys.has('KeyS')||keys.has('ArrowDown'))y++;return{x,y};}
function frame(now){const elapsed=Math.max(0,Math.min((now-previous)/1000,.1));previous=now;const begin=performance.now();const active=!document.hidden&&!$('#app-dialog').open;accumulator=Math.min(.1,accumulator+elapsed);
  if(game){if(active&&game.state==='running'){const v=input();while(accumulator>=STEP){game.update(STEP,v);accumulator-=STEP;if(game.state!=='running')break;}}else accumulator=0;processEvents(game);transition();renderer.draw(game,elapsed);hudTimer+=elapsed;if(hudTimer>.08){updateHUD();hudTimer=0;}}
  else{if(active&&!renderer.reduced){while(accumulator>=STEP){if(demo.state==='upgrade'){demo.chooseUpgrade(demo.choices[0].id);}demo.player.invincible=9999;demo.update(STEP,{x:0,y:0});accumulator-=STEP;}if(demo.time>70)demo=makeDemo();}processEvents(demo,true);renderer.draw(demo,elapsed,true);}
  frameTime+=performance.now()-begin;elapsedTime+=elapsed;frameCount++;if(frameCount>=90){const ms=frameTime/frameCount;fps=Math.round(frameCount/Math.max(elapsedTime,.001));$('#performance').textContent=game?`${Math.min(120,fps)} FPS · ${game.enemies.length} HOSTILES`:'CANVAS 2D / ORIGINAL ASSETS';if(renderer.quality==='auto'&&(ms>15||fps<42)&&!renderer.autoLow){renderer.autoLow=true;renderer.resize();}frameTime=0;elapsedTime=0;frameCount=0;}requestAnimationFrame(frame);
}
$('#stage').tabIndex=-1;
$('#start-button').addEventListener('click',start);$('#retry-button').addEventListener('click',start);$('#result-home').addEventListener('click',home);$('#resume-button').addEventListener('click',()=>{game?.resume();accumulator=0;transition();});$('#pause-button').addEventListener('click',()=>{game?.pause();transition();});$('#quit-button').addEventListener('click',()=>{if(game){game.state='dead';game.emit('dead');transition();}});
$('#nav-home').addEventListener('click',()=>{if(game?.state==='running'){game.pause();transition();}else if(game&&['paused','upgrade'].includes(game.state)){toast('作戦を終了するには、一時停止画面から終了してください。');}else home();});
$('#dash-button').addEventListener('pointerdown',e=>{e.preventDefault();game?.dash();});$('#dash-button').addEventListener('click',()=>game?.dash());$('#pulse-button').addEventListener('pointerdown',e=>{e.preventDefault();game?.pulse();});$('#pulse-button').addEventListener('click',()=>game?.pulse());$('#upgrade-cards').addEventListener('click',e=>{const b=e.target.closest('[data-upgrade]');if(b)choose(b.dataset.upgrade);});
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$('#mode-title').textContent=MODES[mode].name;$('#mode-description').textContent=MODES[mode].description;audio.effect('choose');}));
$$('.sound-toggle').forEach(b=>b.addEventListener('click',()=>setSound(!settings.sound)));
window.addEventListener('keydown',e=>{if($('#app-dialog').open)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;if(game?.state==='upgrade'&&['Digit1','Digit2','Digit3'].includes(e.code)){const u=game.choices[Number(e.code.at(-1))-1];if(u)choose(u.id);return;}if(['Escape','KeyP'].includes(e.code)&&game){if(game.state==='running')game.pause();else if(game.state==='paused')game.resume();transition();accumulator=0;return;}if(game?.state!=='running')return;keys.add(e.code);if(e.code==='Space')game.dash();if(e.code==='KeyQ')game.pulse();});window.addEventListener('keyup',e=>keys.delete(e.code));
const touchArea=$('#game-canvas');touchArea.addEventListener('pointerdown',e=>{if(game?.state!=='running'||stick.id!==null||$('#app-dialog').open)return;e.preventDefault();const r=$('#stage').getBoundingClientRect();stick.id=e.pointerId;stick.x=e.clientX-r.left;stick.y=e.clientY-r.top;touchArea.setPointerCapture(e.pointerId);const joy=$('#joystick');joy.style.left=stick.x+'px';joy.style.top=stick.y+'px';joy.hidden=false;$('#joystick-knob').style.transform='translate(-50%,-50%)';});
touchArea.addEventListener('pointermove',e=>{if(e.pointerId!==stick.id)return;const r=$('#stage').getBoundingClientRect(),dx=e.clientX-r.left-stick.x,dy=e.clientY-r.top-stick.y,d=Math.hypot(dx,dy),max=42,scale=d>max?max/d:1;movement.x=dx*scale/max;movement.y=dy*scale/max;$('#joystick-knob').style.transform=`translate(calc(-50% + ${dx*scale}px),calc(-50% + ${dy*scale}px))`;});
function release(e){if(e.pointerId===stick.id){stick.id=null;movement.x=movement.y=0;$('#joystick').hidden=true;}}touchArea.addEventListener('pointerup',release);touchArea.addEventListener('pointercancel',release);touchArea.addEventListener('lostpointercapture',release);
function autoPause(){clearInput();if(game?.state==='running'){game.pause();transition();}audio.setActive(false);}
window.addEventListener('blur',autoPause);document.addEventListener('visibilitychange',()=>{if(document.hidden)autoPause();else{previous=performance.now();accumulator=0;audio.setActive(true);}});window.addEventListener('focus',()=>audio.setActive(true));
let resizeQueued=false;new ResizeObserver(()=>{if(resizeQueued)return;resizeQueued=true;requestAnimationFrame(()=>{renderer.resize();if(stick.id!==null){stick.id=null;movement.x=movement.y=0;$('#joystick').hidden=true;}resizeQueued=false;});}).observe($('#stage'));
function openDialog(type){dialogReturn=document.activeElement;if(game?.state==='running'){game.pause();transition();}clearInput();const content=$('#dialog-content');
  if(type==='help'){$('#dialog-kicker').textContent='FIELD MANUAL';content.innerHTML=`<h2 id="dialog-title">灯火を守る、そのために。</h2><p>攻撃は自動。敵から距離を取りながら光の欠片を集め、レベルアップで武器を育てましょう。制限時間を生き抜き、終盤の「夜の主」を倒すと作戦成功です。</p><div class="control-row"><span>移動</span><span><kbd>W A S D</kbd> / <kbd>↑ ↓ ← →</kbd></span></div><div class="control-row"><span>スマートフォン</span><span>画面をドラッグして移動</span></div><div class="control-row"><span>ダッシュ / 一瞬の無敵</span><span><kbd>SPACE</kbd> / 右下ボタン</span></div><div class="control-row"><span>パルス / 周囲を攻撃・欠片を回収</span><span><kbd>Q</kbd> / 右下ボタン</span></div><div class="control-row"><span>一時停止</span><span><kbd>P</kbd> / <kbd>ESC</kbd></span></div><div class="control-row"><span>強化を選択</span><span><kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> / タップ</span></div><h3>同じ武器を、もう一度。</h3><p>武器はLv.5で進化します。赤い弾を避け、緑の欠片で成長。十字の種はHPを回復します。パルスはピンチを切り抜ける切り札です。</p><h3>あなたのポケットに、灯火を。</h3><p>インストール対応ブラウザではアプリとして追加できます。iPhone / iPadはSafariの共有メニューから「ホーム画面に追加」。初回読み込み後、オフラインでも遊べます。</p>`;}
  else if(type==='settings'){$('#dialog-kicker').textContent='MAKE IT YOURS';content.innerHTML=`<h2 id="dialog-title">この夜の、設定。</h2><div class="settings-row"><div><label for="setting-sound">サウンド</label><small>BGMと効果音</small></div><input id="setting-sound" type="checkbox" ${settings.sound?'checked':''}></div><div class="settings-row"><label for="setting-music">音楽</label><input id="setting-music" type="range" min="0" max="100" value="${Math.round(settings.music*100)}"></div><div class="settings-row"><label for="setting-sfx">効果音</label><input id="setting-sfx" type="range" min="0" max="100" value="${Math.round(settings.sfx*100)}"></div><div class="settings-row"><div><label for="setting-quality">描画品質</label><small>低品質は電池と処理負荷を抑えます</small></div><select id="setting-quality"><option value="auto">自動</option><option value="high">高品質</option><option value="low">低品質</option></select></div><div class="settings-row"><div><label for="setting-vibration">ダメージ時の振動</label><small>対応する端末のみ</small></div><input id="setting-vibration" type="checkbox" ${settings.vibration?'checked':''}></div><p class="settings-note">設定はこの端末に保存されます。画面を離れると自動で一時停止します。</p>`;$('#setting-quality').value=settings.quality;
    $('#setting-sound').addEventListener('change',e=>setSound(e.target.checked));$('#setting-music').addEventListener('input',e=>{settings.music=e.target.value/100;audio.musicVolume=settings.music;audio.applyVolumes();save('lastlight-settings-v1',settings);});$('#setting-sfx').addEventListener('input',e=>{settings.sfx=e.target.value/100;audio.sfxVolume=settings.sfx;audio.applyVolumes();save('lastlight-settings-v1',settings);});$('#setting-quality').addEventListener('change',e=>{settings.quality=e.target.value;renderer.setQuality(settings.quality);save('lastlight-settings-v1',settings);});$('#setting-vibration').addEventListener('change',e=>{settings.vibration=e.target.checked;save('lastlight-settings-v1',settings);});}
  else{$('#dialog-kicker').textContent='YOUR EXPEDITIONS';content.innerHTML=`<h2 id="dialog-title">灯火の、足跡。</h2><div class="record-grid"><div class="record-tile"><small>最長生存</small><strong>${formatTime(records.bestTime)}</strong></div><div class="record-tile"><small>最多撃破</small><strong>${records.bestKills.toLocaleString()}</strong></div><div class="record-tile"><small>出撃回数</small><strong>${records.runs}</strong></div><div class="record-tile"><small>作戦成功</small><strong>${records.wins}</strong></div></div><div class="record-list">${Object.entries(MODES).map(([id,m])=>`<div><span>${m.name} ${records.modes[id]?.won?'✦':''}</span><span>${records.modes[id]?formatTime(records.modes[id].time):'— — : — —'}</span></div>`).join('')}</div><p class="record-note">記録はこのブラウザに保存されます。端末間の同期はありません。</p>`;}
  $('#app-dialog').showModal();}
$$('[data-dialog]').forEach(b=>b.addEventListener('click',()=>openDialog(b.dataset.dialog)));$('#dialog-close').addEventListener('click',()=>$('#app-dialog').close());$('#app-dialog').addEventListener('click',e=>{if(e.target===$('#app-dialog')){const r=$('#app-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#app-dialog').close();}});$('#app-dialog').addEventListener('close',()=>{clearInput();dialogReturn?.focus({preventScroll:true});previous=performance.now();accumulator=0;});
function connection(){const label=navigator.onLine?'LOCAL / READY':'OFFLINE / READY';$('#connection span').textContent=label;}
window.addEventListener('online',connection);window.addEventListener('offline',connection);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-button').hidden=false;});$('#install-button').addEventListener('click',async()=>{if(!installPrompt)return;await installPrompt.prompt();const result=await installPrompt.userChoice;if(result.outcome==='accepted')$('#install-button').hidden=true;installPrompt=null;});window.addEventListener('appinstalled',()=>{$('#install-button').hidden=true;toast('灯火をホーム画面に追加しました。');});
if('serviceWorker' in navigator){window.addEventListener('load',async()=>{try{const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});function ready(worker){waitingSW=worker;$('#pwa-update').hidden=false;}if(registration.waiting)ready(registration.waiting);registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)ready(worker);});});let reloading=false,hadController=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!hadController){hadController=true;return;}if(reloading)return;if(game&&['running','paused','upgrade'].includes(game.state)){pendingReload=true;$('#pwa-update').hidden=false;toast('更新は作戦終了後に適用できます。');return;}reloading=true;location.reload();});}catch{toast('オフライン保存を利用できません。オンラインではプレイできます。');}});}
$('#update-button').addEventListener('click',()=>{if(game&&['running','paused','upgrade'].includes(game.state)){game.pause();transition();toast('作戦終了後に更新してください。');return;}if(pendingReload)location.reload();else waitingSW?.postMessage({type:'SKIP_WAITING'});});
syncSound();updateBest();connection();requestAnimationFrame(frame);
// Live module bindings are available to development tools without global hooks.
export { game, renderer, audio, settings, records };
